# Generated by Django 5.2.17 on 2026-09-25 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('couple_id', models.AutoField(db_column='coupleID', primary_key=True, serialize=False)),
                ('date_of_start', models.DateField(db_column='dateOfStart')),
                ('partner', models.ForeignKey(db_column='partner_id', on_delete=django.db.models.deletion.CASCADE, related_name='first_partner', to='users.user')),
                ('second_partner', models.ForeignKey(db_column='sPartner_id', on_delete=django.db.models.deletion.CASCADE, related_name='second_partner', to='users.user')),
            ],
        ),
    ]
