# Generated by Django 5.2.17 on 2026-09-25 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('col_id', models.IntegerField(db_column='colID', primary_key=True, serialize=False)),
                ('col_text', models.CharField(db_column='colText', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Repeat',
            fields=[
                ('rep_id', models.IntegerField(db_column='repID', primary_key=True, serialize=False)),
                ('rep_text', models.CharField(db_column='repText', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.UUIDField(db_column='planID', editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.TextField(db_column='planName')),
                ('deadline', models.DateTimeField(db_column='deadline')),
                ('plan_note', models.CharField(db_column='planNote', max_length=255)),
                ('couple', models.ForeignKey(db_column='coupleID', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='couples.couple')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarPlan',
            fields=[
                ('calendar_plan_id', models.IntegerField(db_column='calendarPlanID', primary_key=True, serialize=False)),
                ('date_of_start', models.DateTimeField(db_column='dateOfStart')),
                ('date_of_end', models.DateTimeField(db_column='dateOfEnd')),
                ('color', models.ForeignKey(db_column='color_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_plans', to='plans.color')),
                ('plan', models.ForeignKey(db_column='planID', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_plans', to='plans.plan')),
                ('repeat', models.ForeignKey(db_column='repeat_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_plans', to='plans.repeat')),
            ],
        ),
    ]
