# Generated by Django 5.2.17 on 2026-09-25 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('list_id', models.UUIDField(db_column='listID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('couple', models.ForeignKey(db_column='coupleID', on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='couples.couple')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ForeignKey(db_column='listID', on_delete=django.db.models.deletion.CASCADE, related_name='option', to='lists.list')),
            ],
        ),
    ]
