# Generated by Django 5.2.17 on 2026-09-25 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('wish_id', models.UUIDField(db_column='wishID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('wish_name', models.TextField()),
                ('price', models.IntegerField()),
                ('wish_note', models.TextField()),
                ('couple', models.ForeignKey(db_column='coupleID', on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='couples.couple')),
            ],
        ),
        migrations.CreateModel(
            name='WishPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_photo_link', models.TextField(db_column='wishPhotoLink')),
                ('wish', models.ForeignKey(db_column='wishID', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='wishes.wish')),
            ],
        ),
    ]
