# Generated by Django 5.2.17 on 2026-09-25 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngType',
            fields=[
                ('type_id', models.IntegerField(db_column='typeID', primary_key=True, serialize=False)),
                ('type_name', models.CharField(db_column='typeName', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeType',
            fields=[
                ('type_id', models.IntegerField(db_column='typeID', primary_key=True, serialize=False)),
                ('type_name', models.CharField(db_column='typeName', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ing_id', models.UUIDField(db_column='ingID', editable=False, primary_key=True, serialize=False)),
                ('ing_name', models.CharField(db_column='ingName', max_length=255)),
                ('ing_type', models.ForeignKey(db_column='ingType', on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='menu.ingtype')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.UUIDField(db_column='recipeID', editable=False, primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(db_column='recipeName', max_length=255)),
                ('recipe_link', models.CharField(db_column='recipeLink', max_length=255)),
                ('recipe_note', models.CharField(db_column='recipeNote', max_length=255)),
                ('recipe_type', models.ForeignKey(db_column='recipeType', on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='menu.recipetype')),
            ],
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_amount', models.IntegerField(db_column='ingAmount')),
                ('couple', models.ForeignKey(db_column='coupleID', on_delete=django.db.models.deletion.CASCADE, related_name='fridge', to='couples.couple')),
                ('ingredient', models.ForeignKey(db_column='ingID', on_delete=django.db.models.deletion.CASCADE, related_name='fridge_entries', to='menu.ingredients')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ingredient', 'couple'), name='unique_ingredient_in_fridge')],
            },
        ),
        migrations.CreateModel(
            name='IngInRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_amount', models.IntegerField(db_column='ingAmount')),
                ('ingredient', models.ForeignKey(db_column='ingID', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='menu.ingredients')),
                ('recipe', models.ForeignKey(db_column='recipeID', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.recipes')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredient_in_recipe')],
            },
        ),
    ]
