# Generated by Django 5.2.17 on 2026-09-25 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileid', models.UUIDField(db_column='fileID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField()),
                ('file_type', models.CharField()),
                ('file_URL', models.CharField()),
                ('file_note', models.TextField()),
                ('file_original_name', models.CharField()),
                ('couple', models.ForeignKey(db_column='coupleID', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='couples.couple')),
            ],
        ),
    ]
